In [1]:
###################################
# IMPORT
###################################
from polars import col, concat, lit, when
import polars as pl

import sys; sys.path.append('.'); 
import scripts.hdb_helpers as dc
import os

In [2]:
###################################
# DATA LOAD
###################################
hdbdata = pl.read_parquet('datalake/hdb/raw/hdbdata')
hdbdata.glimpse()
# Updated snapshot PROFILING done on date: #2026-07-17

Rows: 459007
Columns: 13
$ month               <str> '2000-01', '2000-01', '2000-01', '2000-01', '2000-01', '2000-01', '2000-01', '2000-01', '2000-01', '2000-01'
$ town                <str> 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO', 'ANG MO KIO'
$ flat_type           <str> '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM', '3 ROOM'
$ block               <str> '170', '174', '216', '215', '218', '320', '320', '330', '330', '332'
$ street_name         <str> 'ANG MO KIO AVE 4', 'ANG MO KIO AVE 4', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1', 'ANG MO KIO AVE 1'
$ storey_range        <str> '07 TO 09', '04 TO 06', '07 TO 09', '07 TO 09', '07 TO 09', '04 TO 06', '07 TO 09', '07 TO 09', '04 TO 06', '07 TO 09'
$ floor_area_sqm      <f64> 69.0, 61.0, 73.0, 73.0, 67.0, 73.0, 73.0, 68.0, 68.0, 82.0
$ flat_model          <str> 'Improved', 'Improved', 'New Generation', 'New Generation', 'New Generation', 'New Generation', 'New Generation', 'New Generation', 'New Generation', 'New Generation'
$ lease_commence_date <i64> 1986, 1986, 1976, 1976, 1976, 1977, 1977, 1981, 1981, 1981
$ resale_price        <f64> 147000.0, 144000.0, 159000.0, 167000.0, 163000.0, 157000.0, 178000.0, 160000.0, 169000.0, 205000.0
$ tabling_version     <i32> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2
$ remaining_lease     <i64> null, null, null, null, null, null, null, null, null, null
$ record_id           <str> '002-000000', '002-000001', '002-000002', '002-000003', '002-000004', '002-000005', '002-000006', '002-000007', '002-000008', '002-000009'

In [3]:
'''
REQUIREMENT:  Perform Data PROFILING on the dataset. You may code your own PROFILING rules or leverage on
open-source data quality frameworks.
'''

'''
We do first these three entry time PROFILING which might be better done self coded rather than packaged frameworoks and fuller summaries.
row counts -> column name and column types -> time variable
'''

'\nWe do first these three entry time PROFILING which might be better done self coded rather than packaged frameworoks and fuller summaries.\nrow counts -> column name and column types -> time variable\n'

In [4]:
####################################
# PROFILING: row count
####################################

# Q: How much row counts we are looking at.
row_count = (hdbdata
             .group_by('tabling_version')
             .len()
             .sort('tabling_version')
)
print(row_count)
# conclude: nothing alarming

shape: (3, 2)
┌─────────────────┬────────┐
│ tabling_version ┆ len    │
│ ---             ┆ ---    │
│ i32             ┆ u32    │
╞═════════════════╪════════╡
│ 2               ┆ 369651 │
│ 3               ┆ 52203  │
│ 4               ┆ 37153  │
└─────────────────┴────────┘

In [5]:
####################################
# PROFILING: column names and column types
####################################

# Q: What column names and what column types are we looking at?
columnDescribe = pl.DataFrame({
    'column': hdbdata.columns,
    'dtype': [str(dt) for dt in hdbdata.dtypes],
}).sort('dtype')

columnDescribe.show(100)
# conclude good: column names are all in snake case. 
# Consistent and good formatting helps ease of programming. no change required

# conclude: We only have 11 columns (excluding record_id and tabling_version) — 
# this is a narrow dataset, not a wide one with 20-50+ attributes)

# conclude: The only column name which potentially represents the time attribute for the dataset is [month].
# Note: if there were others, we will catch them in the profiling below.


# For the rest which do not represent the time attribute for the dataset -

# Q: are there any numerics which might be better as factors (String)
# ┌─────────────────────┬─────────┐
# │ column              ┆ dtype   │
# │ ---                 ┆ ---     │
# │ str                 ┆ str     │
# ╞═════════════════════╪═════════╡
# │ floor_area_sqm      ┆ Float64 │
# │ resale_price        ┆ Float64 │
# │ lease_commence_year ┆ Int64   │
# │ remaining_lease     ┆ Int64   │

# conclude: by context of column names, these are sensibly numeric, 
# assigned of the correct set of dtypes. No concerns.

# Q: are there any String type which should be numerical but is parsed as String?
# - regardless of the reason it was so.

# │ town                ┆ String  │
# │ flat_type           ┆ String  │
# │ block               ┆ String  │
# │ street_name         ┆ String  │
# │ storey_range        ┆ String  │
# │ flat_model          ┆ String  │

# conclude: by context of column names, these are sensibly textual, 
# assigned of the correct dtype of string. No concerns.

column,dtype
str,str
"""floor_area_sqm""","""Float64"""
"""resale_price""","""Float64"""
"""tabling_version""","""Int32"""
"""lease_commence_date""","""Int64"""
"""remaining_lease""","""Int64"""
"""month""","""String"""
"""town""","""String"""
"""flat_type""","""String"""
"""block""","""String"""
"""street_name""","""String"""
"""storey_range""","""String"""
"""flat_model""","""String"""
"""record_id""","""String"""

In [6]:
####################################
### PROFILING: time variable
####################################
# Let us profile the cleanliness of the time variable.
# then let us profile the row count per month

monthvalues = (hdbdata
             .group_by('month', maintain_order=True)
             .len()
)

In [7]:
# Q: What is the format of the time variable
dc.showall(monthvalues)
# conclude: it specifies the month of the record.
# conclude good: the year-month format is in one consistent form - no variances.
# conclude good: The format is immediately sortable into earlier and later, unlike formats like January 2013
# Downstream validation: Let month be only allowed input format 'YYYY-MM'.

shape: (204, 2)
┌─────────┬──────┐
│ month   ┆ len  │
│ ---     ┆ ---  │
│ str     ┆ u32  │
╞═════════╪══════╡
│ 2000-01 ┆ 2386 │
│ 2000-02 ┆ 2313 │
│ 2000-03 ┆ 2467 │
│ 2000-04 ┆ 2548 │
│ 2000-05 ┆ 3230 │
│ 2000-06 ┆ 3283 │
│ 2000-07 ┆ 2988 │
│ 2000-08 ┆ 3166 │
│ 2000-09 ┆ 3088 │
│ 2000-10 ┆ 3231 │
│ 2000-11 ┆ 3324 │
│ 2000-12 ┆ 2838 │
│ 2001-01 ┆ 2790 │
│ 2001-02 ┆ 2885 │
│ 2001-03 ┆ 3147 │
│ 2001-04 ┆ 3092 │
│ 2001-05 ┆ 3106 │
│ 2001-06 ┆ 3329 │
│ 2001-07 ┆ 3398 │
│ 2001-08 ┆ 3244 │
│ 2001-09 ┆ 3220 │
│ 2001-10 ┆ 3490 │
│ 2001-11 ┆ 3349 │
│ 2001-12 ┆ 3005 │
│ 2002-01 ┆ 3385 │
│ 2002-02 ┆ 2633 │
│ 2002-03 ┆ 3115 │
│ 2002-04 ┆ 3300 │
│ 2002-05 ┆ 3298 │
│ 2002-06 ┆ 2836 │
│ 2002-07 ┆ 3282 │
│ 2002-08 ┆ 2829 │
│ 2002-09 ┆ 2749 │
│ 2002-10 ┆ 3156 │
│ 2002-11 ┆ 2831 │
│ 2002-12 ┆ 2684 │
│ 2003-01 ┆ 2705 │
│ 2003-02 ┆ 1858 │
│ 2003-03 ┆ 2270 │
│ 2003-04 ┆ 2160 │
│ 2003-05 ┆ 2272 │
│ 2003-06 ┆ 2162 │
│ 2003-07 ┆ 2273 │
│ 2003-08 ┆ 2195 │
│ 2003-09 ┆ 2423 │
│ 2003-10 ┆ 2849 │
│ 2003-11 ┆ 2801 │
│ 2003-12 ┆ 3035 │
│ 2004-01 ┆ 2659 │
│ 2004-02 ┆ 2757 │
│ 2004-03 ┆ 2775 │
│ 2004-04 ┆ 2195 │
│ 2004-05 ┆ 2143 │
│ 2004-06 ┆ 2206 │
│ 2004-07 ┆ 2321 │
│ 2004-08 ┆ 2238 │
│ 2004-09 ┆ 2382 │
│ 2004-10 ┆ 2441 │
│ 2004-11 ┆ 2426 │
│ 2004-12 ┆ 2569 │
│ 2005-01 ┆ 2754 │
│ 2005-02 ┆ 2316 │
│ 2005-03 ┆ 2977 │
│ 2005-04 ┆ 2491 │
│ 2005-05 ┆ 2320 │
│ 2005-06 ┆ 2564 │
│ 2005-07 ┆ 2375 │
│ 2005-08 ┆ 2559 │
│ 2005-09 ┆ 2512 │
│ 2005-10 ┆ 2506 │
│ 2005-11 ┆ 2408 │
│ 2005-12 ┆ 2263 │
│ 2006-01 ┆ 2039 │
│ 2006-02 ┆ 2183 │
│ 2006-03 ┆ 2463 │
│ 2006-04 ┆ 2093 │
│ 2006-05 ┆ 2406 │
│ 2006-06 ┆ 2546 │
│ 2006-07 ┆ 2400 │
│ 2006-08 ┆ 2452 │
│ 2006-09 ┆ 2418 │
│ 2006-10 ┆ 2190 │
│ 2006-11 ┆ 2284 │
│ 2006-12 ┆ 1953 │
│ 2007-01 ┆ 2289 │
│ 2007-02 ┆ 1933 │
│ 2007-03 ┆ 2364 │
│ 2007-04 ┆ 2066 │
│ 2007-05 ┆ 2164 │
│ 2007-06 ┆ 2224 │
│ 2007-07 ┆ 2364 │
│ 2007-08 ┆ 2523 │
│ 2007-09 ┆ 2361 │
│ 2007-10 ┆ 2442 │
│ 2007-11 ┆ 2322 │
│ 2007-12 ┆ 1930 │
│ 2008-01 ┆ 2285 │
│ 2008-02 ┆ 2028 │
│ 2008-03 ┆ 2145 │
│ 2008-04 ┆ 2341 │
│ 2008-05 ┆ 2178 │
│ 2008-06 ┆ 2270 │
│ 2008-07 ┆ 2458 │
│ 2008-08 ┆ 2197 │
│ 2008-09 ┆ 2492 │
│ 2008-10 ┆ 2395 │
│ 2008-11 ┆ 2424 │
│ 2008-12 ┆ 2049 │
│ 2009-01 ┆ 2006 │
│ 2009-02 ┆ 1817 │
│ 2009-03 ┆ 2480 │
│ 2009-04 ┆ 2299 │
│ 2009-05 ┆ 2222 │
│ 2009-06 ┆ 2440 │
│ 2009-07 ┆ 2672 │
│ 2009-08 ┆ 2550 │
│ 2009-09 ┆ 2916 │
│ 2009-10 ┆ 3432 │
│ 2009-11 ┆ 2853 │
│ 2009-12 ┆ 2795 │
│ 2010-01 ┆ 2825 │
│ 2010-02 ┆ 2418 │
│ 2010-03 ┆ 3264 │
│ 2010-04 ┆ 3036 │
│ 2010-05 ┆ 2812 │
│ 2010-06 ┆ 3517 │
│ 2010-07 ┆ 3679 │
│ 2010-08 ┆ 3298 │
│ 2010-09 ┆ 3002 │
│ 2010-10 ┆ 2773 │
│ 2010-11 ┆ 2208 │
│ 2010-12 ┆ 2022 │
│ 2011-01 ┆ 2131 │
│ 2011-02 ┆ 1747 │
│ 2011-03 ┆ 1991 │
│ 2011-04 ┆ 1980 │
│ 2011-05 ┆ 1958 │
│ 2011-06 ┆ 2026 │
│ 2011-07 ┆ 1996 │
│ 2011-08 ┆ 1730 │
│ 2011-09 ┆ 1790 │
│ 2011-10 ┆ 1615 │
│ 2011-11 ┆ 1745 │
│ 2011-12 ┆ 1572 │
│ 2012-01 ┆ 1559 │
│ 2012-02 ┆ 1629 │
│ 2012-03 ┆ 2360 │
│ 2012-04 ┆ 2155 │
│ 2012-05 ┆ 2323 │
│ 2012-06 ┆ 1993 │
│ 2012-07 ┆ 2179 │
│ 2012-08 ┆ 2075 │
│ 2012-09 ┆ 1760 │
│ 2012-10 ┆ 1937 │
│ 2012-11 ┆ 1735 │
│ 2012-12 ┆ 1493 │
│ 2013-01 ┆ 1633 │
│ 2013-02 ┆ 886  │
│ 2013-03 ┆ 1306 │
│ 2013-04 ┆ 1692 │
│ 2013-05 ┆ 1605 │
│ 2013-06 ┆ 1317 │
│ 2013-07 ┆ 1484 │
│ 2013-08 ┆ 1354 │
│ 2013-09 ┆ 1212 │
│ 2013-10 ┆ 1391 │
│ 2013-11 ┆ 1209 │
│ 2013-12 ┆ 1008 │
│ 2014-01 ┆ 1098 │
│ 2014-02 ┆ 959  │
│ 2014-03 ┆ 1444 │
│ 2014-04 ┆ 1557 │
│ 2014-05 ┆ 1447 │
│ 2014-06 ┆ 1223 │
│ 2014-07 ┆ 1352 │
│ 2014-08 ┆ 1329 │
│ 2014-09 ┆ 1472 │
│ 2014-10 ┆ 1560 │
│ 2014-11 ┆ 1351 │
│ 2014-12 ┆ 1304 │
│ 2015-01 ┆ 1250 │
│ 2015-02 ┆ 1151 │
│ 2015-03 ┆ 1348 │
│ 2015-04 ┆ 1630 │
│ 2015-05 ┆ 1567 │
│ 2015-06 ┆ 1706 │
│ 2015-07 ┆ 1551 │
│ 2015-08 ┆ 1449 │
│ 2015-09 ┆ 1498 │
│ 2015-10 ┆ 1748 │
│ 2015-11 ┆ 1470 │
│ 2015-12 ┆ 1412 │
│ 2016-01 ┆ 1280 │
│ 2016-02 ┆ 1200 │
│ 2016-03 ┆ 1655 │
│ 2016-04 ┆ 1824 │
│ 2016-05 ┆ 1829 │
│ 2016-06 ┆ 1827 │
│ 2016-07 ┆ 1572 │
│ 2016-08 ┆ 1882 │
│ 2016-09 ┆ 1668 │
│ 2016-10 ┆ 1678 │
│ 2016-11 ┆ 1580 │
│ 2016-12 ┆ 1378 │
└─────────┴──────┘

In [8]:
# Q: Is there any anomalous row counts in any month?
monthvalues['len'].describe()
# conclude: Average records in a month = 2273
# Max records in a month = 3679, nothing alarmig yet
# Min records in a month: 886, nothing alarming yet
# Note: min was coming not from earliest the month in the records. 
# Hence it is not due to cutoff in early data collection. nothing alarming.
# Nothing alarming overall.

shape: (9, 2)
┌────────────┬─────────────┐
│ statistic  ┆ value       │
│ ---        ┆ ---         │
│ str        ┆ f64         │
╞════════════╪═════════════╡
│ count      ┆ 204.0       │
│ null_count ┆ 0.0         │
│ mean       ┆ 2250.034314 │
│ std        ┆ 624.331993  │
│ min        ┆ 886.0       │
│ 25%        ┆ 1747.0      │
│ 50%        ┆ 2273.0      │
│ 75%        ┆ 2684.0      │
│ max        ┆ 3679.0      │
└────────────┴─────────────┘

In [9]:
# Q: what is the time span of the dataset:
min_max_month = (hdbdata
               .sort('tabling_version')
               .group_by('tabling_version')
               .agg(
                 pl.min('month').alias('1st_month'),
                 pl.max('month').alias('last_month'),
             )
)

print(min_max_month)
# conclude good: tables 1,2,3 are linked in continuity. No concerns.
# conclude: earliest data is 2000-01 latest data is 2016-12.
# downstream action: will scope it out to only 2012-01 onwards for table 2. In script 2_data_cleaning.

shape: (3, 3)
┌─────────────────┬───────────┬────────────┐
│ tabling_version ┆ 1st_month ┆ last_month │
│ ---             ┆ ---       ┆ ---        │
│ i32             ┆ str       ┆ str        │
╞═════════════════╪═══════════╪════════════╡
│ 2               ┆ 2000-01   ┆ 2012-02    │
│ 3               ┆ 2012-03   ┆ 2014-12    │
│ 4               ┆ 2015-01   ┆ 2016-12    │
└─────────────────┴───────────┴────────────┘

In [10]:
# Q: Are there any gaps in the monthly time series?
data_exists_monthdate = (
    hdbdata
    .select('month').unique()
    .with_columns(monthdate = col('month').str.strptime(pl.Date, '%Y-%m'))
    .sort('monthdate')
    .with_columns(in_data = lit(1))
)


complete_monthdate_list = (
    pl.date_range(
        data_exists_monthdate['monthdate'].min(),
        data_exists_monthdate['monthdate'].max(),
        interval='1mo',
        eager=True,
    )
    .alias('monthdate').to_frame()
)

monthdate_indicator = complete_monthdate_list.join(data_exists_monthdate, on='monthdate', how='left')

In [11]:
dc.showall(monthdate_indicator)
# conclude good: By full visual check, confirm every month is in the datas. Also every month format is correct.

shape: (204, 3)
┌────────────┬─────────┬─────────┐
│ monthdate  ┆ month   ┆ in_data │
│ ---        ┆ ---     ┆ ---     │
│ date       ┆ str     ┆ i32     │
╞════════════╪═════════╪═════════╡
│ 2000-01-01 ┆ 2000-01 ┆ 1       │
│ 2000-02-01 ┆ 2000-02 ┆ 1       │
│ 2000-03-01 ┆ 2000-03 ┆ 1       │
│ 2000-04-01 ┆ 2000-04 ┆ 1       │
│ 2000-05-01 ┆ 2000-05 ┆ 1       │
│ 2000-06-01 ┆ 2000-06 ┆ 1       │
│ 2000-07-01 ┆ 2000-07 ┆ 1       │
│ 2000-08-01 ┆ 2000-08 ┆ 1       │
│ 2000-09-01 ┆ 2000-09 ┆ 1       │
│ 2000-10-01 ┆ 2000-10 ┆ 1       │
│ 2000-11-01 ┆ 2000-11 ┆ 1       │
│ 2000-12-01 ┆ 2000-12 ┆ 1       │
│ 2001-01-01 ┆ 2001-01 ┆ 1       │
│ 2001-02-01 ┆ 2001-02 ┆ 1       │
│ 2001-03-01 ┆ 2001-03 ┆ 1       │
│ 2001-04-01 ┆ 2001-04 ┆ 1       │
│ 2001-05-01 ┆ 2001-05 ┆ 1       │
│ 2001-06-01 ┆ 2001-06 ┆ 1       │
│ 2001-07-01 ┆ 2001-07 ┆ 1       │
│ 2001-08-01 ┆ 2001-08 ┆ 1       │
│ 2001-09-01 ┆ 2001-09 ┆ 1       │
│ 2001-10-01 ┆ 2001-10 ┆ 1       │
│ 2001-11-01 ┆ 2001-11 ┆ 1       │
│ 2001-12-01 ┆ 2001-12 ┆ 1       │
│ 2002-01-01 ┆ 2002-01 ┆ 1       │
│ 2002-02-01 ┆ 2002-02 ┆ 1       │
│ 2002-03-01 ┆ 2002-03 ┆ 1       │
│ 2002-04-01 ┆ 2002-04 ┆ 1       │
│ 2002-05-01 ┆ 2002-05 ┆ 1       │
│ 2002-06-01 ┆ 2002-06 ┆ 1       │
│ 2002-07-01 ┆ 2002-07 ┆ 1       │
│ 2002-08-01 ┆ 2002-08 ┆ 1       │
│ 2002-09-01 ┆ 2002-09 ┆ 1       │
│ 2002-10-01 ┆ 2002-10 ┆ 1       │
│ 2002-11-01 ┆ 2002-11 ┆ 1       │
│ 2002-12-01 ┆ 2002-12 ┆ 1       │
│ 2003-01-01 ┆ 2003-01 ┆ 1       │
│ 2003-02-01 ┆ 2003-02 ┆ 1       │
│ 2003-03-01 ┆ 2003-03 ┆ 1       │
│ 2003-04-01 ┆ 2003-04 ┆ 1       │
│ 2003-05-01 ┆ 2003-05 ┆ 1       │
│ 2003-06-01 ┆ 2003-06 ┆ 1       │
│ 2003-07-01 ┆ 2003-07 ┆ 1       │
│ 2003-08-01 ┆ 2003-08 ┆ 1       │
│ 2003-09-01 ┆ 2003-09 ┆ 1       │
│ 2003-10-01 ┆ 2003-10 ┆ 1       │
│ 2003-11-01 ┆ 2003-11 ┆ 1       │
│ 2003-12-01 ┆ 2003-12 ┆ 1       │
│ 2004-01-01 ┆ 2004-01 ┆ 1       │
│ 2004-02-01 ┆ 2004-02 ┆ 1       │
│ 2004-03-01 ┆ 2004-03 ┆ 1       │
│ 2004-04-01 ┆ 2004-04 ┆ 1       │
│ 2004-05-01 ┆ 2004-05 ┆ 1       │
│ 2004-06-01 ┆ 2004-06 ┆ 1       │
│ 2004-07-01 ┆ 2004-07 ┆ 1       │
│ 2004-08-01 ┆ 2004-08 ┆ 1       │
│ 2004-09-01 ┆ 2004-09 ┆ 1       │
│ 2004-10-01 ┆ 2004-10 ┆ 1       │
│ 2004-11-01 ┆ 2004-11 ┆ 1       │
│ 2004-12-01 ┆ 2004-12 ┆ 1       │
│ 2005-01-01 ┆ 2005-01 ┆ 1       │
│ 2005-02-01 ┆ 2005-02 ┆ 1       │
│ 2005-03-01 ┆ 2005-03 ┆ 1       │
│ 2005-04-01 ┆ 2005-04 ┆ 1       │
│ 2005-05-01 ┆ 2005-05 ┆ 1       │
│ 2005-06-01 ┆ 2005-06 ┆ 1       │
│ 2005-07-01 ┆ 2005-07 ┆ 1       │
│ 2005-08-01 ┆ 2005-08 ┆ 1       │
│ 2005-09-01 ┆ 2005-09 ┆ 1       │
│ 2005-10-01 ┆ 2005-10 ┆ 1       │
│ 2005-11-01 ┆ 2005-11 ┆ 1       │
│ 2005-12-01 ┆ 2005-12 ┆ 1       │
│ 2006-01-01 ┆ 2006-01 ┆ 1       │
│ 2006-02-01 ┆ 2006-02 ┆ 1       │
│ 2006-03-01 ┆ 2006-03 ┆ 1       │
│ 2006-04-01 ┆ 2006-04 ┆ 1       │
│ 2006-05-01 ┆ 2006-05 ┆ 1       │
│ 2006-06-01 ┆ 2006-06 ┆ 1       │
│ 2006-07-01 ┆ 2006-07 ┆ 1       │
│ 2006-08-01 ┆ 2006-08 ┆ 1       │
│ 2006-09-01 ┆ 2006-09 ┆ 1       │
│ 2006-10-01 ┆ 2006-10 ┆ 1       │
│ 2006-11-01 ┆ 2006-11 ┆ 1       │
│ 2006-12-01 ┆ 2006-12 ┆ 1       │
│ 2007-01-01 ┆ 2007-01 ┆ 1       │
│ 2007-02-01 ┆ 2007-02 ┆ 1       │
│ 2007-03-01 ┆ 2007-03 ┆ 1       │
│ 2007-04-01 ┆ 2007-04 ┆ 1       │
│ 2007-05-01 ┆ 2007-05 ┆ 1       │
│ 2007-06-01 ┆ 2007-06 ┆ 1       │
│ 2007-07-01 ┆ 2007-07 ┆ 1       │
│ 2007-08-01 ┆ 2007-08 ┆ 1       │
│ 2007-09-01 ┆ 2007-09 ┆ 1       │
│ 2007-10-01 ┆ 2007-10 ┆ 1       │
│ 2007-11-01 ┆ 2007-11 ┆ 1       │
│ 2007-12-01 ┆ 2007-12 ┆ 1       │
│ 2008-01-01 ┆ 2008-01 ┆ 1       │
│ 2008-02-01 ┆ 2008-02 ┆ 1       │
│ 2008-03-01 ┆ 2008-03 ┆ 1       │
│ 2008-04-01 ┆ 2008-04 ┆ 1       │
│ 2008-05-01 ┆ 2008-05 ┆ 1       │
│ 2008-06-01 ┆ 2008-06 ┆ 1       │
│ 2008-07-01 ┆ 2008-07 ┆ 1       │
│ 2008-08-01 ┆ 2008-08 ┆ 1       │
│ 2008-09-01 ┆ 2008-09 ┆ 1       │
│ 2008-10-01 ┆ 2008-10 ┆ 1       │
│ 2008-11-01 ┆ 2008-11 ┆ 1       │
│ 2008-12-01 ┆ 2008-12 ┆ 1       │
│ 2009-01-01 ┆ 2009-01 ┆ 1       │
│ 2009-02-01 ┆ 2009-02 ┆ 1       │
│ 2009-03-01 ┆ 2009-03 ┆ 1       │
│ 2009-04-01 ┆ 2009-04 ┆ 1       │
│ 2009-05-01 ┆ 2009-05 ┆ 1       │
│ 2009-06-01 ┆ 2009-06 ┆ 1       │
│ 2009-07-01 ┆ 2009-07 ┆ 1       │
│ 2009-08-01 ┆ 2009-08 ┆ 1       │
│ 2009-09-01 ┆ 2009-09 ┆ 1       │
│ 2009-10-01 ┆ 2009-10 ┆ 1       │
│ 2009-11-01 ┆ 2009-11 ┆ 1       │
│ 2009-12-01 ┆ 2009-12 ┆ 1       │
│ 2010-01-01 ┆ 2010-01 ┆ 1       │
│ 2010-02-01 ┆ 2010-02 ┆ 1       │
│ 2010-03-01 ┆ 2010-03 ┆ 1       │
│ 2010-04-01 ┆ 2010-04 ┆ 1       │
│ 2010-05-01 ┆ 2010-05 ┆ 1       │
│ 2010-06-01 ┆ 2010-06 ┆ 1       │
│ 2010-07-01 ┆ 2010-07 ┆ 1       │
│ 2010-08-01 ┆ 2010-08 ┆ 1       │
│ 2010-09-01 ┆ 2010-09 ┆ 1       │
│ 2010-10-01 ┆ 2010-10 ┆ 1       │
│ 2010-11-01 ┆ 2010-11 ┆ 1       │
│ 2010-12-01 ┆ 2010-12 ┆ 1       │
│ 2011-01-01 ┆ 2011-01 ┆ 1       │
│ 2011-02-01 ┆ 2011-02 ┆ 1       │
│ 2011-03-01 ┆ 2011-03 ┆ 1       │
│ 2011-04-01 ┆ 2011-04 ┆ 1       │
│ 2011-05-01 ┆ 2011-05 ┆ 1       │
│ 2011-06-01 ┆ 2011-06 ┆ 1       │
│ 2011-07-01 ┆ 2011-07 ┆ 1       │
│ 2011-08-01 ┆ 2011-08 ┆ 1       │
│ 2011-09-01 ┆ 2011-09 ┆ 1       │
│ 2011-10-01 ┆ 2011-10 ┆ 1       │
│ 2011-11-01 ┆ 2011-11 ┆ 1       │
│ 2011-12-01 ┆ 2011-12 ┆ 1       │
│ 2012-01-01 ┆ 2012-01 ┆ 1       │
│ 2012-02-01 ┆ 2012-02 ┆ 1       │
│ 2012-03-01 ┆ 2012-03 ┆ 1       │
│ 2012-04-01 ┆ 2012-04 ┆ 1       │
│ 2012-05-01 ┆ 2012-05 ┆ 1       │
│ 2012-06-01 ┆ 2012-06 ┆ 1       │
│ 2012-07-01 ┆ 2012-07 ┆ 1       │
│ 2012-08-01 ┆ 2012-08 ┆ 1       │
│ 2012-09-01 ┆ 2012-09 ┆ 1       │
│ 2012-10-01 ┆ 2012-10 ┆ 1       │
│ 2012-11-01 ┆ 2012-11 ┆ 1       │
│ 2012-12-01 ┆ 2012-12 ┆ 1       │
│ 2013-01-01 ┆ 2013-01 ┆ 1       │
│ 2013-02-01 ┆ 2013-02 ┆ 1       │
│ 2013-03-01 ┆ 2013-03 ┆ 1       │
│ 2013-04-01 ┆ 2013-04 ┆ 1       │
│ 2013-05-01 ┆ 2013-05 ┆ 1       │
│ 2013-06-01 ┆ 2013-06 ┆ 1       │
│ 2013-07-01 ┆ 2013-07 ┆ 1       │
│ 2013-08-01 ┆ 2013-08 ┆ 1       │
│ 2013-09-01 ┆ 2013-09 ┆ 1       │
│ 2013-10-01 ┆ 2013-10 ┆ 1       │
│ 2013-11-01 ┆ 2013-11 ┆ 1       │
│ 2013-12-01 ┆ 2013-12 ┆ 1       │
│ 2014-01-01 ┆ 2014-01 ┆ 1       │
│ 2014-02-01 ┆ 2014-02 ┆ 1       │
│ 2014-03-01 ┆ 2014-03 ┆ 1       │
│ 2014-04-01 ┆ 2014-04 ┆ 1       │
│ 2014-05-01 ┆ 2014-05 ┆ 1       │
│ 2014-06-01 ┆ 2014-06 ┆ 1       │
│ 2014-07-01 ┆ 2014-07 ┆ 1       │
│ 2014-08-01 ┆ 2014-08 ┆ 1       │
│ 2014-09-01 ┆ 2014-09 ┆ 1       │
│ 2014-10-01 ┆ 2014-10 ┆ 1       │
│ 2014-11-01 ┆ 2014-11 ┆ 1       │
│ 2014-12-01 ┆ 2014-12 ┆ 1       │
│ 2015-01-01 ┆ 2015-01 ┆ 1       │
│ 2015-02-01 ┆ 2015-02 ┆ 1       │
│ 2015-03-01 ┆ 2015-03 ┆ 1       │
│ 2015-04-01 ┆ 2015-04 ┆ 1       │
│ 2015-05-01 ┆ 2015-05 ┆ 1       │
│ 2015-06-01 ┆ 2015-06 ┆ 1       │
│ 2015-07-01 ┆ 2015-07 ┆ 1       │
│ 2015-08-01 ┆ 2015-08 ┆ 1       │
│ 2015-09-01 ┆ 2015-09 ┆ 1       │
│ 2015-10-01 ┆ 2015-10 ┆ 1       │
│ 2015-11-01 ┆ 2015-11 ┆ 1       │
│ 2015-12-01 ┆ 2015-12 ┆ 1       │
│ 2016-01-01 ┆ 2016-01 ┆ 1       │
│ 2016-02-01 ┆ 2016-02 ┆ 1       │
│ 2016-03-01 ┆ 2016-03 ┆ 1       │
│ 2016-04-01 ┆ 2016-04 ┆ 1       │
│ 2016-05-01 ┆ 2016-05 ┆ 1       │
│ 2016-06-01 ┆ 2016-06 ┆ 1       │
│ 2016-07-01 ┆ 2016-07 ┆ 1       │
│ 2016-08-01 ┆ 2016-08 ┆ 1       │
│ 2016-09-01 ┆ 2016-09 ┆ 1       │
│ 2016-10-01 ┆ 2016-10 ┆ 1       │
│ 2016-11-01 ┆ 2016-11 ┆ 1       │
│ 2016-12-01 ┆ 2016-12 ┆ 1       │
└────────────┴─────────┴─────────┘

In [12]:
check_12_months_within_year = (
    monthdate_indicator
    .with_columns(year=col('monthdate').dt.year())
    .group_by('year', maintain_order=True)
    .len()
)
dc.showall(check_12_months_within_year)
# conclude good: By more concise check, all years has all and only 12 months, => every month is in the data.

# conclude good: no gaps reported.

print('row counts -> column name and column types -> time variable')
print('In these three specifics, no concerns were yet raised, so there is nothing to triage.')

shape: (17, 2)
┌──────┬─────┐
│ year ┆ len │
│ ---  ┆ --- │
│ i32  ┆ u32 │
╞══════╪═════╡
│ 2000 ┆ 12  │
│ 2001 ┆ 12  │
│ 2002 ┆ 12  │
│ 2003 ┆ 12  │
│ 2004 ┆ 12  │
│ 2005 ┆ 12  │
│ 2006 ┆ 12  │
│ 2007 ┆ 12  │
│ 2008 ┆ 12  │
│ 2009 ┆ 12  │
│ 2010 ┆ 12  │
│ 2011 ┆ 12  │
│ 2012 ┆ 12  │
│ 2013 ┆ 12  │
│ 2014 ┆ 12  │
│ 2015 ┆ 12  │
│ 2016 ┆ 12  │
└──────┴─────┘
row counts -> column name and column types -> time variable
In these three specifics, no concerns were yet raised, so there is nothing to triage.

In [13]:
'''
We now deal with categorical and numerical data profiling
We will now use an external tool which provides more details for lesser work.
We will use the ProfileReport function from the ydata-profiling package to easier and quickly generate the views we need.
'''

'''
# Author note. I  understand the project requests to do work programmatically as much as possible;
# However, i wish to use also ydata_profile to showcase that i am capable in 
# a) leverage [open-source data quality frameworks] and  
# b) integrating out-of-code processes with pipelines as seamlessly as I can.
'''

'\n# Author note. I  understand the project requests to do work programmatically as much as possible;\n# However, i wish to use also ydata_profile to showcase that i am capable in \n# a) leverage [open-source data quality frameworks] and  \n# b) integrating out-of-code processes with pipelines as seamlessly as I can.\n'

In [14]:
from ydata_profiling import ProfileReport

profile = ProfileReport(
    hdbdata.to_pandas(),
    title='HDB Resale Master Dataset - Data Profile',
)

os.makedirs('output', exist_ok=True)
profile.to_file('output/hdb_ydataprofile_report.html')

/Users/murftech/Root/production/hdb_assess_submission/venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

/var/folders/b2/jxsmc4xx49v5lrwhc889dxt00000gn/T/ipykernel_55396/493005442.py:1: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

Summarize dataset:   0%|                                                                                                                                      | 0/5 [00:00<?, ?it/s]

Summarize dataset:   0%|                                                                                                           | 0/18 [00:00<?, ?it/s, Describe variable: month]

Summarize dataset:   0%|                                                                                                     | 0/18 [00:00<?, ?it/s, Describe variable: street_name]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

Summarize dataset:   0%|                                                                                                      | 0/18 [00:00<?, ?it/s, Describe variable: flat_model]

  0%|                                                                                                                                                        | 0/13 [00:00<?, ?it/s]

Summarize dataset:   6%|█████▏                                                                                        | 1/18 [00:02<00:47,  2.80s/it, Describe variable: flat_model]

Summarize dataset:  11%|█████████▍                                                                           | 2/18 [00:02<00:28,  1.78s/it, Describe variable: lease_commence_date]

Summarize dataset:  11%|██████████▏                                                                                 | 2/18 [00:02<00:28,  1.78s/it, Describe variable: resale_price]

Summarize dataset:  11%|██████████▏                                                                                 | 2/18 [00:03<00:28,  1.78s/it, Describe variable: resale_price]

Summarize dataset:  28%|█████████████████████████▌                                                                  | 5/18 [00:03<00:04,  2.69it/s, Describe variable: resale_price]

Summarize dataset:  39%|██████████████████████████████████▌                                                      | 7/18 [00:03<00:01,  7.11it/s, Describe variable: tabling_version]

Summarize dataset:  39%|██████████████████████████████████▌                                                      | 7/18 [00:03<00:01,  7.11it/s, Describe variable: remaining_lease]

Summarize dataset:  39%|████████████████████████████████████▉                                                          | 7/18 [00:03<00:01,  7.11it/s, Describe variable: record_id]

Summarize dataset:  39%|████████████████████████████████████▉                                                          | 7/18 [00:03<00:01,  7.11it/s, Describe variable: record_id]

Summarize dataset:  39%|████████████████████████████████████▉                                                          | 7/18 [00:03<00:01,  7.11it/s, Describe variable: record_id]

Summarize dataset:  39%|████████████████████████████████████▉                                                          | 7/18 [00:03<00:01,  7.11it/s, Describe variable: record_id]

Summarize dataset:  39%|████████████████████████████████████▉                                                          | 7/18 [00:03<00:01,  7.11it/s, Describe variable: record_id]

Summarize dataset:  50%|███████████████████████████████████████████████▌                                               | 9/18 [00:03<00:01,  6.57it/s, Describe variable: record_id]

  8%|███████████                                                                                                                                     | 1/13 [00:01<00:17,  1.44s/it]

Summarize dataset:  67%|██████████████████████████████████████████████████████████████▋                               | 12/18 [00:03<00:00,  7.90it/s, Describe variable: record_id]

 77%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████                                 | 10/13 [00:01<00:00,  7.98it/s]

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.70it/s]

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:02<00:00,  4.51it/s]

Summarize dataset:  72%|███████████████████████████████████████████████████████████████████████████                             | 13/18 [00:04<00:00,  7.90it/s, Get variable types]

Summarize dataset:  74%|████████████████████████████████████████████████████████████████████████████▋                           | 14/19 [00:04<00:01,  4.18it/s, Get variable types]

Summarize dataset:  74%|████████████████████████████████████████████████████████████████████████▏                         | 14/19 [00:04<00:01,  4.18it/s, Get dataframe statistics]

Summarize dataset:  75%|████████████████████████████████████████████████████████████████████████                        | 15/20 [00:04<00:01,  4.18it/s, Calculate auto correlation]

/Users/murftech/Root/production/hdb_assess_submission/venv/lib/python3.13/site-packages/ydata_profiling/model/pandas/discretize_pandas.py:52: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 9 9 9]' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  discretized_df.loc[:, column] = self._discretize_column(

Summarize dataset:  80%|████████████████████████████████████████████████████████████████████████████▊                   | 16/20 [00:06<00:01,  2.91it/s, Calculate auto correlation]

Summarize dataset:  80%|███████████████████████████████████████████████████████████████████████████████████▏                    | 16/20 [00:06<00:01,  2.91it/s, Get scatter matrix]

Summarize dataset:  44%|█████████████████████████████████████▎                                              | 16/36 [00:06<00:06,  2.91it/s, scatter floor_area_sqm, floor_area_sqm]

Summarize dataset:  47%|█████████████████████████████████████▎                                         | 17/36 [00:06<00:06,  2.91it/s, scatter lease_commence_date, floor_area_sqm]

Summarize dataset:  50%|███████████████████████████████████████▌                                       | 18/36 [00:06<00:04,  3.70it/s, scatter lease_commence_date, floor_area_sqm]

Summarize dataset:  50%|███████████████████████████████████████████                                           | 18/36 [00:06<00:04,  3.70it/s, scatter resale_price, floor_area_sqm]

Summarize dataset:  53%|█████████████████████████████████████████████▍                                        | 19/36 [00:06<00:04,  4.05it/s, scatter resale_price, floor_area_sqm]

Summarize dataset:  53%|███████████████████████████████████████████▊                                       | 19/36 [00:06<00:04,  4.05it/s, scatter remaining_lease, floor_area_sqm]

Summarize dataset:  56%|███████████████████████████████████████████▉                                   | 20/36 [00:06<00:03,  4.05it/s, scatter floor_area_sqm, lease_commence_date]

Summarize dataset:  58%|███████████████████████████████████████████▏                              | 21/36 [00:06<00:03,  4.05it/s, scatter lease_commence_date, lease_commence_date]

Summarize dataset:  61%|█████████████████████████████████████████████▏                            | 22/36 [00:06<00:02,  5.96it/s, scatter lease_commence_date, lease_commence_date]

Summarize dataset:  61%|█████████████████████████████████████████████████▌                               | 22/36 [00:06<00:02,  5.96it/s, scatter resale_price, lease_commence_date]

Summarize dataset:  64%|█████████████████████████████████████████████████▊                            | 23/36 [00:06<00:02,  5.96it/s, scatter remaining_lease, lease_commence_date]

Summarize dataset:  67%|█████████████████████████████████████████████████████████▎                            | 24/36 [00:06<00:02,  5.96it/s, scatter floor_area_sqm, resale_price]

Summarize dataset:  69%|███████████████████████████████████████████████████████████▋                          | 25/36 [00:06<00:01,  7.95it/s, scatter floor_area_sqm, resale_price]

Summarize dataset:  69%|████████████████████████████████████████████████████████▎                        | 25/36 [00:06<00:01,  7.95it/s, scatter lease_commence_date, resale_price]

Summarize dataset:  72%|███████████████████████████████████████████████████████████████▌                        | 26/36 [00:06<00:01,  7.95it/s, scatter resale_price, resale_price]

Summarize dataset:  75%|██████████████████████████████████████████████████████████████████                      | 27/36 [00:06<00:00,  9.17it/s, scatter resale_price, resale_price]

Summarize dataset:  75%|███████████████████████████████████████████████████████████████▊                     | 27/36 [00:06<00:00,  9.17it/s, scatter remaining_lease, resale_price]

Summarize dataset:  78%|████████████████████████████████████████████████████████████████▌                  | 28/36 [00:06<00:00,  9.17it/s, scatter floor_area_sqm, remaining_lease]

Summarize dataset:  81%|██████████████████████████████████████████████████████████████▊               | 29/36 [00:07<00:00,  9.17it/s, scatter lease_commence_date, remaining_lease]

Summarize dataset:  83%|█████████████████████████████████████████████████████████████████             | 30/36 [00:07<00:00, 11.96it/s, scatter lease_commence_date, remaining_lease]

Summarize dataset:  83%|██████████████████████████████████████████████████████████████████████▊              | 30/36 [00:07<00:00, 11.96it/s, scatter resale_price, remaining_lease]

Summarize dataset:  86%|██████████████████████████████████████████████████████████████████████▌           | 31/36 [00:07<00:00, 11.96it/s, scatter remaining_lease, remaining_lease]

Summarize dataset:  84%|██████████████████████████████████████████████████████████████████████████████████████▋                | 32/38 [00:07<00:00, 11.96it/s, Missing diagram bar]

Summarize dataset:  87%|█████████████████████████████████████████████████████████████████████████████████████████▍             | 33/38 [00:07<00:00, 12.65it/s, Missing diagram bar]

Summarize dataset:  87%|██████████████████████████████████████████████████████████████████████████████████████▊             | 33/38 [00:07<00:00, 12.65it/s, Missing diagram matrix]

Summarize dataset:  89%|███████████████████████████████████████████████████████████████████████████████████████████████████▎           | 34/38 [00:07<00:00, 12.65it/s, Take sample]

Summarize dataset:  92%|██████████████████████████████████████████████████████████████████████████████████████████████████████▏        | 35/38 [00:07<00:00,  8.51it/s, Take sample]

Summarize dataset:  92%|█████████████████████████████████████████████████████████████████████████████████████████████▉        | 35/38 [00:07<00:00,  8.51it/s, Detecting duplicates]

Summarize dataset:  95%|██████████████████████████████████████████████████████████████████████████████████████████████████████████      | 36/38 [00:07<00:00,  8.51it/s, Get alerts]

Summarize dataset:  97%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████   | 37/38 [00:07<00:00,  8.95it/s, Get alerts]

Summarize dataset:  97%|███████████████████████████████████████████████████████████████████████████████████████████████▍  | 37/38 [00:07<00:00,  8.95it/s, Get reproduction details]

Summarize dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:07<00:00,  8.95it/s, Completed]

Summarize dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 38/38 [00:07<00:00,  4.80it/s, Completed]

Generate report structure:   0%|                                                                                                                              | 0/1 [00:00<?, ?it/s]

Generate report structure: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.38s/it]

Generate report structure: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.39s/it]

Render HTML:   0%|                                                                                                                                            | 0/1 [00:00<?, ?it/s]

Render HTML: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.52it/s]

Render HTML: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.48it/s]

Export report to file:   0%|                                                                                                                                  | 0/1 [00:00<?, ?it/s]

Export report to file: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 152.65it/s]

In [15]:
# openfile = 'false'
openfile = 'true'
if openfile == 'true':
    import os
    os.system('open output/hdb_ydataprofile_report.html')

In [16]:
'''
# Becasue the report of this tool is static file based, 
# we need to take screenshots portions from the report and give the profiling decision in-line 
# in a file type like microsoft word docx.
# i have done the exercise in this document: output/hdb_ydataprofile_report_downstream.docx
# To review the decisions, please open the docx file if you already have an associated app installed - with the command below:
'''

# openfile = 'false'
openfile = 'true'
if openfile == 'true':
    import os
    os.system('open output/hdb_ydataprofile_report_downstream.docx')

In [17]:
###################################
# Profiling: Categorical Variable
###################################

# Categorical variable: 
# Cardinality Q1: does the number of distinct values make sense. Is the only all-applicable question.
# Cardinality Q2: Does any of them became near to a row key?
# String hiding the type? Which should be a number, numeric, time but got saved as a string in source.
# Long Tails, of potentially inconsequential values.
# Format/Casing Inconsistency
# Is it a valid member

In [18]:
'''
Followup from: output/hdb_ydataprofile_report_downstream.docx

# storey_range
# Downstream profiling: We will investigate in code if all values are of this pattern.

# flat_model
# Downstream profiling: We will investigate in code if there are long tail of rare values, 
# which we then ask if they are candidates for merging with other 
'''

'\nFollowup from: output/hdb_ydataprofile_report_downstream.docx\n\n# storey_range\n# Downstream profiling: We will investigate in code if all values are of this pattern.\n\n# flat_model\n# Downstream profiling: We will investigate in code if there are long tail of rare values, \n# which we then ask if they are candidates for merging with other \n'

In [19]:
# storey_range
# Downstream profiling: We will investigate in code if all values are of this pattern dd TO dd.
hdbdata['storey_range'].value_counts().sort('count').show(1000)
# conclude: Yes. 
# Downstream validation: Let storey_range be only allowed input format as such eg '28 TO 30'.

storey_range,count
str,u32
"""31 TO 35""",2
"""49 TO 51""",2
"""36 TO 40""",7
"""43 TO 45""",8
"""46 TO 48""",8
"""26 TO 30""",39
"""40 TO 42""",50
"""21 TO 25""",92
"""37 TO 39""",103
"""34 TO 36""",107
"""31 TO 33""",107
"""16 TO 20""",265
"""28 TO 30""",668
"""11 TO 15""",1259
"""25 TO 27""",1404
"""06 TO 10""",2474
"""01 TO 05""",2700
"""22 TO 24""",3241
"""19 TO 21""",5328
"""16 TO 18""",11637
"""13 TO 15""",31001
"""10 TO 12""",86633
"""01 TO 03""",93548
"""07 TO 09""",102771
"""04 TO 06""",115553

In [20]:
# flat_model
# Downstream profiling: We will investigate in code if there are long tail of rare values, 
# which we then ask if they are candidates for merging with others

hdbdata['flat_model'].value_counts().sort('count').show(1000)
# ANS: yes there are.

# ANS: Several of these are really variants of the same base design rather than fully independent categories, 
# So that they're natural merge candidates if we look for another grouping with fewer buckets:
# However this is a decision to be made later by stakeholders. 
# Since they are all real HDB flat_model names, there is no need to edit this column.

# ┌────────────────────────┬────────┐
# │ flat_model             ┆ count  │
# │ ---                    ┆ ---    │
# │ str                    ┆ u32    │
# ╞════════════════════════╪════════╡
# │ Premium Apartment Loft ┆ 5      │ Potentially a rare value
# │ 2-room                 ┆ 17     │ Potentially a rare value
# │ Type S2                ┆ 55     │ Potentially a rare value
# │ ImPROVEd-Maisonette    ┆ 56     │ Potentially a rare value
# │ Premium Maisonette     ┆ 72     │ Potentially a rare value
# │ Type S1                ┆ 138    │ 
# │ Multi Generation       ┆ 186    │
# │ DBSS                   ┆ 277    │
# │ Terrace                ┆ 349    │
# │ Model A-Maisonette     ┆ 771    │
# │ Adjoined flat          ┆ 933    │
# │ Model A2               ┆ 8064   │
# │ Maisonette             ┆ 12318  │
# │ Apartment              ┆ 18846  │
# │ Standard               ┆ 20219  │
# │ Premium Apartment      ┆ 26340  │
# │ Simplified             ┆ 27334  │
# │ New Generation         ┆ 87611  │
# │ ImPROVEd               ┆ 123696 │
# │ Model A                ┆ 131720 │
# └────────────────────────┴────────┘

flat_model,count
str,u32
"""Premium Apartment Loft""",5
"""2-room""",17
"""Type S2""",55
"""Improved-Maisonette""",56
"""Premium Maisonette""",72
"""Type S1""",138
"""Multi Generation""",186
"""DBSS""",277
"""Terrace""",349
"""Model A-Maisonette""",771
"""Adjoined flat""",933
"""Model A2""",8064
"""Maisonette""",12318
"""Apartment""",18846
"""Standard""",20219
"""Premium Apartment""",26340
"""Simplified""",27334
"""New Generation""",87611
"""Improved""",123696
"""Model A""",131720

In [21]:


###################################
# Profiling: Categorical Variable
###################################

# Numeric variable: 



hdbdata

shape: (459_007, 13)
┌─────────┬────────┬─────────────┬───────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ month   ┆ town   ┆ flat_type   ┆ block ┆ … ┆ resale_pric ┆ tabling_ver ┆ remaining_ ┆ record_id  │
│ ---     ┆ ---    ┆ ---         ┆ ---   ┆   ┆ e           ┆ sion        ┆ lease      ┆ ---        │
│ str     ┆ str    ┆ str         ┆ str   ┆   ┆ ---         ┆ ---         ┆ ---        ┆ str        │
│         ┆        ┆             ┆       ┆   ┆ f64         ┆ i32         ┆ i64        ┆            │
╞═════════╪════════╪═════════════╪═══════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 2000-01 ┆ ANG MO ┆ 3 ROOM      ┆ 170   ┆ … ┆ 147000.0    ┆ 2           ┆ null       ┆ 002-000000 │
│         ┆ KIO    ┆             ┆       ┆   ┆             ┆             ┆            ┆            │
│ 2000-01 ┆ ANG MO ┆ 3 ROOM      ┆ 174   ┆ … ┆ 144000.0    ┆ 2           ┆ null       ┆ 002-000001 │
│         ┆ KIO    ┆             ┆       ┆   ┆             ┆             ┆            ┆            │
│ 2000-01 ┆ ANG MO ┆ 3 ROOM      ┆ 216   ┆ … ┆ 159000.0    ┆ 2           ┆ null       ┆ 002-000002 │
│         ┆ KIO    ┆             ┆       ┆   ┆             ┆             ┆            ┆            │
│ 2000-01 ┆ ANG MO ┆ 3 ROOM      ┆ 215   ┆ … ┆ 167000.0    ┆ 2           ┆ null       ┆ 002-000003 │
│         ┆ KIO    ┆             ┆       ┆   ┆             ┆             ┆            ┆            │
│ 2000-01 ┆ ANG MO ┆ 3 ROOM      ┆ 218   ┆ … ┆ 163000.0    ┆ 2           ┆ null       ┆ 002-000004 │
│         ┆ KIO    ┆             ┆       ┆   ┆             ┆             ┆            ┆            │
│ …       ┆ …      ┆ …           ┆ …     ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ 2016-12 ┆ YISHUN ┆ 5 ROOM      ┆ 297   ┆ … ┆ 488000.0    ┆ 4           ┆ 82         ┆ 004-459002 │
│ 2016-12 ┆ YISHUN ┆ 5 ROOM      ┆ 838   ┆ … ┆ 455000.0    ┆ 4           ┆ 69         ┆ 004-459003 │
│ 2016-12 ┆ YISHUN ┆ EXECUTIVE   ┆ 664   ┆ … ┆ 778000.0    ┆ 4           ┆ 74         ┆ 004-459004 │
│ 2016-12 ┆ YISHUN ┆ EXECUTIVE   ┆ 325   ┆ … ┆ 575000.0    ┆ 4           ┆ 70         ┆ 004-459005 │
│ 2016-12 ┆ YISHUN ┆ MULTI-GENER ┆ 666   ┆ … ┆ 735000.0    ┆ 4           ┆ 70         ┆ 004-459006 │
│         ┆        ┆ ATION       ┆       ┆   ┆             ┆             ┆            ┆            │
└─────────┴────────┴─────────────┴───────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [22]:
###################################
# Profiling: Numeric Variable - resale_price IQR by year and flat_type
###################################

'''
RQUIREMENT: Identify any potentially anomalous resale price based on any heuristics you deem
appropriate. Please document your heuristic and assumptions in your documentations.
'''

## There is a most robust quick method to have a first flag. That is the 1.5*IQR fence method.
## We assume that prices could increase or drop by year. Year to be taken as consideration.
## We assume that prices of bigger flats are more expensive than smaller flats. flat_type to be taken into consideration.
## within each cohort of year and flattype, we apply 1.5*IQR to quickly flag out potential anomalous resale prices.

'\nRQUIREMENT: Identify any potentially anomalous resale price based on any heuristics you deem\nappropriate. Please document your heuristic and assumptions in your documentations.\n'

In [23]:
hdb_sel = hdbdata.select('month', 'record_id', 'flat_type', 'resale_price')

resale_price_iqr = (
    hdb_sel
    .with_columns(year=col('month').str.slice(0, 4))
    .with_columns(
        group_samplesize = pl.len().over(['year', 'flat_type']),
        q1=col('resale_price').quantile(0.25, interpolation='linear').over(['year', 'flat_type']),
        group_median = pl.median('resale_price').over(['year', 'flat_type']),
        q3=col('resale_price').quantile(0.75, interpolation='linear').over(['year', 'flat_type']),
    )
    .with_columns(iqr=col('q3') - col('q1'))
    .with_columns(
        upp_1_5_iqr=col('q1') - 1.5 * col('iqr'),
        low_1_5_iqr=col('q3') + 1.5 * col('iqr'),
    )
    .with_columns(
        is_outlier=(col('resale_price') < col('upp_1_5_iqr')) | (col('resale_price') > col('low_1_5_iqr'))
    )
)

dc.sortcount(resale_price_iqr, 'is_outlier')
# validate
dc.showall(resale_price_iqr.filter(col('is_outlier')==True), 'closey')

459007
shape: (2, 3)
┌────────────┬────────┬──────────┐
│ is_outlier ┆ count  ┆ pcnt     │
│ ---        ┆ ---    ┆ ---      │
│ bool       ┆ u32    ┆ f64      │
╞════════════╪════════╪══════════╡
│ false      ┆ 438771 ┆ 0.955914 │
│ true       ┆ 20236  ┆ 0.044086 │
└────────────┴────────┴──────────┘
shape: (20_236, 13)
┌─────────┬────────────┬───────────┬──────────────┬──────┬──────────────────┬──────────┬──────────────┬──────────┬──────────┬─────────────┬─────────────┬────────────┐
│ month   ┆ record_id  ┆ flat_type ┆ resale_price ┆ year ┆ group_samplesize ┆ q1       ┆ group_median ┆ q3       ┆ iqr      ┆ upp_1_5_iqr ┆ low_1_5_iqr ┆ is_outlier │
│ ---     ┆ ---        ┆ ---       ┆ ---          ┆ ---  ┆ ---              ┆ ---      ┆ ---          ┆ ---      ┆ ---      ┆ ---         ┆ ---         ┆ ---        │
│ str     ┆ str        ┆ str       ┆ f64          ┆ str  ┆ u32              ┆ f64      ┆ f64          ┆ f64      ┆ f64      ┆ f64         ┆ f64         ┆ bool       │
╞═════════╪════════════╪═══════════╪══════════════╪══════╪══════════════════╪══════════╪══════════════╪══════════╪══════════╪═════════════╪═════════════╪════════════╡
│ 2000-01 ┆ 002-000055 ┆ 3 ROOM    ┆ 222500.0     ┆ 2000 ┆ 12423            ┆ 142000.0 ┆ 156000.0     ┆ 170000.0 ┆ 28000.0  ┆ 100000.0    ┆ 212000.0    ┆ true       │
│ 2000-01 ┆ 002-000063 ┆ 3 ROOM    ┆ 238000.0     ┆ 2000 ┆ 12423            ┆ 142000.0 ┆ 156000.0     ┆ 170000.0 ┆ 28000.0  ┆ 100000.0    ┆ 212000.0    ┆ true       │
│ 2000-01 ┆ 002-000088 ┆ 3 ROOM    ┆ 236000.0     ┆ 2000 ┆ 12423            ┆ 142000.0 ┆ 156000.0     ┆ 170000.0 ┆ 28000.0  ┆ 100000.0    ┆ 212000.0    ┆ true       │
│ 2000-01 ┆ 002-000159 ┆ 2 ROOM    ┆ 126500.0     ┆ 2000 ┆ 278              ┆ 75050.0  ┆ 83000.0      ┆ 94750.0  ┆ 19700.0  ┆ 45500.0     ┆ 124300.0    ┆ true       │
│ 2000-01 ┆ 002-000192 ┆ 3 ROOM    ┆ 218000.0     ┆ 2000 ┆ 12423            ┆ 142000.0 ┆ 156000.0     ┆ 170000.0 ┆ 28000.0  ┆ 100000.0    ┆ 212000.0    ┆ true       │
│ …       ┆ …          ┆ …         ┆ …            ┆ …    ┆ …                ┆ …        ┆ …            ┆ …        ┆ …        ┆ …           ┆ …           ┆ …          │
│ 2016-12 ┆ 004-458810 ┆ 4 ROOM    ┆ 715000.0     ┆ 2016 ┆ 8050             ┆ 365000.0 ┆ 405000.0     ┆ 462000.0 ┆ 97000.0  ┆ 219500.0    ┆ 607500.0    ┆ true       │
│ 2016-12 ┆ 004-458811 ┆ 4 ROOM    ┆ 628000.0     ┆ 2016 ┆ 8050             ┆ 365000.0 ┆ 405000.0     ┆ 462000.0 ┆ 97000.0  ┆ 219500.0    ┆ 607500.0    ┆ true       │
│ 2016-12 ┆ 004-458816 ┆ 5 ROOM    ┆ 880000.0     ┆ 2016 ┆ 4585             ┆ 430000.0 ┆ 475000.0     ┆ 565000.0 ┆ 135000.0 ┆ 227500.0    ┆ 767500.0    ┆ true       │
│ 2016-12 ┆ 004-458817 ┆ 5 ROOM    ┆ 820888.0     ┆ 2016 ┆ 4585             ┆ 430000.0 ┆ 475000.0     ┆ 565000.0 ┆ 135000.0 ┆ 227500.0    ┆ 767500.0    ┆ true       │
│ 2016-12 ┆ 004-458820 ┆ EXECUTIVE ┆ 900000.0     ┆ 2016 ┆ 1489             ┆ 550000.0 ┆ 600000.0     ┆ 680000.0 ┆ 130000.0 ┆ 355000.0    ┆ 875000.0    ┆ true       │
└─────────┴────────────┴───────────┴──────────────┴──────┴──────────────────┴──────────┴──────────────┴──────────┴──────────┴─────────────┴─────────────┴────────────┘

In [24]:
# Q: How many records fall outside their cohort's 1.5*IQR fence, overall and by group, if we use simple IQR fence?
outlier_summary = (
    resale_price_iqr
    .group_by('year', maintain_order=True)
    .agg(
        n=pl.len(),
        n_outlier=col('is_outlier').sum(),
    )
    .with_columns(pcnt_outlier=(col('n_outlier') / col('n')))
    .sort(['year'])
)

dc.showall(outlier_summary)


print(f"total records flagged as outlier: {resale_price_iqr['is_outlier'].sum():,} "
      f"out of {resale_price_iqr.height:,} ({resale_price_iqr['is_outlier'].mean():.2%})")

# conclude:
# downstream action: decide stakeholders how could we further the rules to decide on flagging outlier or even dropping data.
# in script 2_data_validation
# no action taken as of now

shape: (17, 4)
┌──────┬───────┬───────────┬──────────────┐
│ year ┆ n     ┆ n_outlier ┆ pcnt_outlier │
│ ---  ┆ ---   ┆ ---       ┆ ---          │
│ str  ┆ u32   ┆ u32       ┆ f64          │
╞══════╪═══════╪═══════════╪══════════════╡
│ 2000 ┆ 34862 ┆ 994       ┆ 0.028512     │
│ 2001 ┆ 38055 ┆ 993       ┆ 0.026094     │
│ 2002 ┆ 36098 ┆ 1000      ┆ 0.027702     │
│ 2003 ┆ 29003 ┆ 775       ┆ 0.026721     │
│ 2004 ┆ 29112 ┆ 753       ┆ 0.025866     │
│ 2005 ┆ 30045 ┆ 1019      ┆ 0.033916     │
│ 2006 ┆ 27427 ┆ 1440      ┆ 0.052503     │
│ 2007 ┆ 26982 ┆ 1609      ┆ 0.059632     │
│ 2008 ┆ 27262 ┆ 1310      ┆ 0.048052     │
│ 2009 ┆ 30482 ┆ 1656      ┆ 0.054327     │
│ 2010 ┆ 34854 ┆ 1629      ┆ 0.046738     │
│ 2011 ┆ 22281 ┆ 1136      ┆ 0.050985     │
│ 2012 ┆ 23198 ┆ 1343      ┆ 0.057893     │
│ 2013 ┆ 16097 ┆ 1024      ┆ 0.063614     │
│ 2014 ┆ 16096 ┆ 934       ┆ 0.058027     │
│ 2015 ┆ 17780 ┆ 1224      ┆ 0.068841     │
│ 2016 ┆ 19373 ┆ 1397      ┆ 0.072111     │
└──────┴───────┴───────────┴──────────────┘
total records flagged as outlier: 20,236 out of 459,007 (4.41%)

In [25]:
'''
END OF SCRIPT.
We have gathered all downstream work, tagged and ctrl+f by downstream.
There is no DATA WRITE in this script. It is also not required in the operationalized pipeline.
It should however be ran out of AWS, on a regular basis, including writing further profiling codes to check for data drifts, new validations required.
'''

'\nEND OF SCRIPT.\nWe have gathered all downstream work, tagged and ctrl+f by downstream.\nThere is no DATA WRITE in this script. It is also not required in the operationalized pipeline.\nIt should however be ran out of AWS, on a regular basis, including writing further profiling codes to check for data drifts, new validations required.\n'